apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crewspace

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - db-secret.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
